### PR TITLE
Fix crash when reading a local file in a production environment (#1)

### PR DESCRIPTION
**Pull request by wynnw**
When using this code in an environment where the python libraries are in a virtualenv where the files are readable but not writable will crash due to a change that was made to use a permissions string of 'rb+'. This file shouldn't be updated by this reader code (I think), so revert it back to 'rb'.

### CODE REVIEW

**Review by davidmegginson — APPROVED** [review]

**Comment by davidmegginson** [comment]
Thank you for catching that! I've merged into the dev branch. It will appear in the semi-stable test branch soon, and in the main branch for the next release.

**Comment by wynnw** [comment]
Awesome, thank you! I look forward to getting rid of my very ugly hack working around this :)

**Comment by davidmegginson** [comment]
> Awesome, thank you! I look forward to getting rid of my very ugly hack working around this :)

Your change is in the _test_ branch now, if you want to switch to it. That branch is reasonably stable (compared to _dev_).

**Comment by wynnw** [comment]
We are using this via the pip installable packages, and my workaround is fine, so we can wait for the official release. Thanks for the tip though.

**Pull request merged**
